---
name: Release Docker Images

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare
        id: prep
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            if [[ $VERSION =~ ^v([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})$ ]]; then
               MAJOR="${BASH_REMATCH[1]}"
               MINOR="${BASH_REMATCH[2]}"
               PATCH="${BASH_REMATCH[3]}"

               TAGS="${{ secrets.DOCKER_IMAGE }}:latest"
               TAGS="${TAGS},${{ secrets.DOCKER_IMAGE }}:v${MAJOR}"
               TAGS="${TAGS},${{ secrets.DOCKER_IMAGE }}:v${MAJOR}.${MINOR}"
               TAGS="${TAGS},${{ secrets.DOCKER_IMAGE }}:v${MAJOR}.${MINOR}.${PATCH}"
               TAGS="${TAGS},${{ secrets.QUAY_IMAGE }}:latest"
               TAGS="${TAGS},${{ secrets.QUAY_IMAGE }}:v${MAJOR}"
               TAGS="${TAGS},${{ secrets.QUAY_IMAGE }}:v${MAJOR}.${MINOR}"
               TAGS="${TAGS},${{ secrets.QUAY_IMAGE }}:v${MAJOR}.${MINOR}.${PATCH}"
            else
               TAGS="${{ secrets.DOCKER_IMAGE }}:${VERSION}"
               TAGS="${TAGS},${{ secrets.QUAY_IMAGE }}:${VERSION}"
            fi
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
            if [ "${{ github.event.repository.default_branch }}" = "$VERSION" ]; then
              VERSION=edge
            fi
            TAGS="${{ secrets.DOCKER_IMAGE }}:${VERSION}"
            TAGS="${TAGS},${{ secrets.QUAY_IMAGE }}:${VERSION}"
          elif [[ $GITHUB_REF == refs/pull/* ]]; then
            VERSION=pr-${{ github.event.number }}
            TAGS="${{ secrets.DOCKER_IMAGE }}:${VERSION}"
            TAGS="${TAGS},${{ secrets.QUAY_IMAGE }}:${VERSION}"
          fi
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=buildtime::$(date -u +'%FT%TZ%:z')
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to docker container registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
      - name: Login to quay container registry
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_REGISTRY_USERNAME }}
          password: ${{ secrets.QUAY_REGISTRY_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.prep.outputs.tags }}
          build-args: |
            APP_NAME=${{ secrets.APP_NAME }}
            PKG=${{ github.repository }}
            VERSION=${{ steps.prep.outputs.version }}
            COMMITHASH=${{ github.sha }}
            BUILDTIME=${{ steps.prep.outputs.buildtime }}
          labels: |
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=${{ github.event.repository.license.spdx_id }}
